#!/bin/sh

set -eu

TCP_PORT="${1:-12345}"
UDP_PORT="${2:-12346}"
UDP_ENABLED="${3:-1}"
MARK_BASE_HEX="${4:-0x52000000}"

OUT="/etc/nftables.d/socks5pbr.nft"

# Build a fw4 include snippet.
#
# Strategy:
# - In `table inet fw4`, set meta mark based on ip saddr -> mark mapping.
# - For packets with our mark, apply tproxy to local port (tcp/udp).
#
# Notes:
# - This is IPv4-first. IPv6 can be added later via `ip6 saddr` map.

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

cat >"$tmp" <<EOF
# Generated by socks5pbr (do not edit)
table inet fw4 {
  map socks5pbr_src_to_mark {
    type ipv4_addr : mark
    elements = {
EOF

# Build map elements from UCI rules.
idx=1
uci -q show socks5pbr | sed -n "s/^socks5pbr\\.@rule\\[\\([0-9]*\\)\\]\\.src_ip='\\(.*\\)'/\\1 \\2/p" | while read -r ridx src_ip; do
  enabled="$(uci -q get socks5pbr.@rule[$ridx].enabled || echo 1)"
  node="$(uci -q get socks5pbr.@rule[$ridx].node || echo '')"
  [ "$enabled" = "1" ] || continue
  [ -n "$node" ] || continue
  # Derive a stable mark per node name by hashing to 16-bit.
  # Busybox has `cksum`; we use it for a deterministic value.
  h="$(printf "%s" "$node" | cksum | awk '{print $1}')"
  mark_low="$(printf "0x%04x" "$((h % 65535 + 1))")"
  echo "      ${src_ip} : ${MARK_BASE_HEX} | ${mark_low}," >>"$tmp"
  idx=$((idx + 1))
done

cat >>"$tmp" <<'EOF'
    }
  }

  chain mangle_prerouting {
    # If a LAN client is configured, assign mark.
    meta mark set ip saddr vmap @socks5pbr_src_to_mark

    # Apply TPROXY for marked flows.
    meta mark & 0xFFFF0000 == __MARK_BASE__ tcp tproxy to :__TCP_PORT__
__UDP_RULE__
  }
}
EOF

if [ "$UDP_ENABLED" = "1" ]; then
  udp_rule="    meta mark & 0xFFFF0000 == __MARK_BASE__ udp tproxy to :__UDP_PORT__"
else
  udp_rule=""
fi

sed -i \
  -e "s/__TCP_PORT__/${TCP_PORT}/g" \
  -e "s/__UDP_PORT__/${UDP_PORT}/g" \
  -e "s/__MARK_BASE__/${MARK_BASE_HEX}/g" \
  -e "s#__UDP_RULE__#${udp_rule}#g" \
  "$tmp"

mkdir -p /etc/nftables.d
mv "$tmp" "$OUT"

exit 0

